### ISSUE TITLE
Refactor _getPageFromOffset method

### ISSUE THREAD

**Issue by vedartm** [excogitatr/rick-and-morty-info#13]
In the file [home_bloc.dart](https://github.com/excogitatr/rick-and-morty-info/blob/develop/lib/features/home/presentation/bloc/home_bloc.dart)
Refactor the function `_getPageFromOffset(int offset)` by adding `+1` inside the function

**Comment by agent515** [comment]
Hey, I would like to work on this issue.
Could you elaborate on how you need refactoring?

**Comment by vedartm** [comment]
It is very simple.. you can check that home_bloc file and change that function.

**Comment by agent515** [comment]
Okay, so you want _getPageFromOffset(offset) to be equivalent to _getPageFromOffset(offset) + 1.
At first, I couldn't help but fail to notice it.. don't know why. 😆 
okay, I'll do that. 👍
