### ISSUE TITLE
Refactor NetworkInfo

### ISSUE THREAD

**Issue by vedartm** [excogitatr/rick-and-morty-info#14]
Remove the interface [INetworkInfo](https://github.com/excogitatr/rick-and-morty-info/blob/develop/lib/core/network/network_info.dart) and refactor the feature and tests accordingly

**Comment by agent515** [comment]
I'll try to resolve this issue.

**Comment by agent515** [comment]
@excogitatr review PR #20 and put a hacktoberfest-accepted label once approved.
