### ISSUE TITLE
Question about the entity model

### ISSUE THREAD

**Issue by smiqueias** [excogitatr/rick-and-morty-info#29]
In the api documentation, the character schema has a list of the episode schema.

If I want to make a query like this:

```
query($page: Int!) {
  characters(page: $page) {
    results {
      id,
      name,
      status,
      species,
      image,
      type,
      episode {
        name,
        air_date,
        episode
        
      }
    }
  }
}
```

Can I insert the List<Episode> field in the character entity, for example?

**Comment by vedartm** [comment]
Yes. You can have a list of episodes entity inside the character entity.
