### ISSUE TITLE
unable to run example with latest version of graphql-flutter

### ISSUE THREAD

**Issue by HBO2** [excogitatr/rick-and-morty-info#6]
I tried to run the app with the new version 1.5 of Flutter and also the latest version of 
graphql-flutter:  ^1.0.0+4

and ran into issues. 

The main issue is the fact the Client is not used in the new graphql-flutter version. and refactor to 
```
static final HttpLink httpLink = HttpLink(
    uri: 'https://rickandmortyapi.com/graphql',
  );
```
is not working.

Are you able to update the example with Flutter 1.5

BTW: using the graphql-flutter version  0.9.5 in combination with Flutter 1.5 gives all kind of errors in the console

thx,  and already thx for the great example.

**Comment by msreekm** [comment]
upgraded to v2.0 and fixed the errors here- 
https://github.com/msreekm/rick-and-morty-info
